version: '3'
services:
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    volumes:
      - ./scripts:/scripts
    command: /bin/bash -c "/scripts/start-kafka.sh"